# Generated by Django 3.0.5 on 2020-07-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_testimonials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonials',
        ),
    ]
